[build]
builder = "nixpacks"
watchPatterns = ["*.py"]

[deploy]
startCommand = "uvicorn langbackend:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
PYTHON_VERSION = "3.10.0"